name: build-python

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: alpine:3.20

    steps:
      - name: Install build dependencies
        run: |
          apk add --no-cache \
          build-base \
          linux-headers \
          openssl-dev \
          zlib-dev \
          bzip2-dev \
          xz-dev \
          readline-dev \
          sqlite-dev \
          libffi-dev \
          wget

      - name: Download Python source
        run: |
          wget https://www.python.org/ftp/python/3.13.0/Python-3.13.0.tgz
          tar -xf Python-3.13.0.tgz

      - name: Build Python
        run: |
          cd Python-3.13.0
          ./configure --prefix=/python313
          make -j$(nproc)
          make install

      - name: Package build
        run: |
          tar -czf python313-musl.tar.gz /python313

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python313-musl
          path: python313-musl.tar.gz
